import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case portuguese = "pt"
    case english = "en"
    case french = "fr"

    var id: String { rawValue }

    var name: String {
        switch self {
        case .portuguese: "Português"
        case .english: "English"
        case .french: "Français"
        }
    }

    static var current: AppLanguage {
        AppLanguage(
            rawValue: UserDefaults.standard.string(forKey: "appLanguage") ?? "pt"
        ) ?? .portuguese
    }
}

func tr(_ key: String) -> String {
    translations[AppLanguage.current]?[key] ?? key
}

private let translations: [AppLanguage: [String: String]] = [
    .english: [
        "Notebooks": "Notebooks",
        "Nova nota": "New note",
        "Novo notebook": "New notebook",
        "Nome do notebook": "Notebook name",
        "Renomear notebook": "Rename notebook",
        "Remover nota": "Delete note",
        "Remover notebook": "Delete notebook",
        "Cor do notebook": "Notebook color",
        "Cor da nota": "Note color",
        "Cor do texto": "Text color",
        "Sem cor": "No color",
        "Vermelho": "Red",
        "Laranja": "Orange",
        "Amarelo": "Yellow",
        "Verde": "Green",
        "Azul": "Blue",
        "Roxo": "Purple",
        "Remover esta nota?": "Delete this note?",
        "A nota e as suas imagens serão movidas para o Lixo.": "The note and its images will be moved to the Trash.",
        "Remover este notebook?": "Delete this notebook?",
        "Todas as notas e imagens deste notebook serão movidas para o Lixo.": "All notes and images in this notebook will be moved to the Trash.",
        "Mover para o Lixo": "Move to Trash",
        "Configurações": "Settings",
        "Selecione uma nota": "Select a note",
        "Editar nota": "Edit note",
        "Visualizar nota": "Preview note",
        "Editor e visualização": "Editor and preview",
        "Desfazer": "Undo",
        "Refazer": "Redo",
        "Cortar": "Cut",
        "Copiar": "Copy",
        "Colar": "Paste",
        "Selecionar tudo": "Select All",
        "palavras": "words",
        "carateres": "characters",
        "linhas": "lines",
        "Lista de tarefas": "Task list",
        "Tabela": "Table",
        "Separador horizontal": "Horizontal rule",
        "Coluna": "Column",
        "Conteúdo": "Content",
        "Título 4": "Heading 4",
        "Título 5": "Heading 5",
        "Título 6": "Heading 6",
        "Parágrafo": "Paragraph",
        "Adicionar bloco": "Add block",
        "Linguagem": "Language",
        "Descrição da imagem": "Image description",
        "Localização da imagem": "Image location",
        "Adicionar linha": "Add row",
        "Adicionar coluna": "Add column",
        "Duplicar bloco": "Duplicate block",
        "Remover bloco": "Delete block",
        "Guardar nota (⌘S)": "Save note (⌘S)",
        "Exportar nota para PDF": "Export note to PDF",
        "Alterações por guardar": "Unsaved changes",
        "Fechar nota": "Close note",
        "Título": "Heading",
        "Título 1": "Heading 1",
        "Título 2": "Heading 2",
        "Título 3": "Heading 3",
        "Negrito": "Bold",
        "Itálico": "Italic",
        "Rasurado": "Strikethrough",
        "Código": "Inline code",
        "Lista": "Bullet list",
        "Lista numerada": "Numbered list",
        "Citação": "Quote",
        "Ligação": "Link",
        "Adicionar imagem": "Add image",
        "Bloco de código": "Code block",
        "Idioma": "Language",
        "Localização das notas": "Notes location",
        "Os notebooks, notas e respetivas imagens serão guardados nesta pasta.": "Notebooks, notes and their images will be stored in this folder.",
        "Nenhuma pasta selecionada": "No folder selected",
        "Selecionar pasta…": "Choose folder…",
        "Para atribuir um nome novo, use o botão Nova Pasta no seletor do Finder.": "To create a new name, use the New Folder button in the Finder picker.",
        "Estrutura planeada: Notebook / Nota / note.md + assets": "Storage structure: Notebook / Note / note.md + assets",
        "Concluído": "Done",
        "Escolher pasta das notas": "Choose notes folder",
        "Escolher": "Choose",
        "Guardar alterações?": "Save changes?",
        "A nota foi alterada desde a última gravação.": "The note has changed since it was last saved.",
        "Guardar": "Save",
        "Não guardar": "Don't Save",
        "Cancelar": "Cancel",
        "Guardar alterações antes de sair?": "Save changes before quitting?",
        "Existem notas com alterações que ainda não foram guardadas.": "Some notes have unsaved changes.",
        "Guardar tudo": "Save All",
        "Não foi possível exportar o PDF": "The PDF could not be exported",
        "Exportar": "Export"
    ],
    .french: [
        "Notebooks": "Carnets",
        "Nova nota": "Nouvelle note",
        "Novo notebook": "Nouveau carnet",
        "Nome do notebook": "Nom du carnet",
        "Renomear notebook": "Renommer le carnet",
        "Remover nota": "Supprimer la note",
        "Remover notebook": "Supprimer le carnet",
        "Cor do notebook": "Couleur du carnet",
        "Cor da nota": "Couleur de la note",
        "Cor do texto": "Couleur du texte",
        "Sem cor": "Sans couleur",
        "Vermelho": "Rouge",
        "Laranja": "Orange",
        "Amarelo": "Jaune",
        "Verde": "Vert",
        "Azul": "Bleu",
        "Roxo": "Violet",
        "Remover esta nota?": "Supprimer cette note ?",
        "A nota e as suas imagens serão movidas para o Lixo.": "La note et ses images seront placées dans la Corbeille.",
        "Remover este notebook?": "Supprimer ce carnet ?",
        "Todas as notas e imagens deste notebook serão movidas para o Lixo.": "Toutes les notes et images de ce carnet seront placées dans la Corbeille.",
        "Mover para o Lixo": "Placer dans la Corbeille",
        "Configurações": "Réglages",
        "Selecione uma nota": "Sélectionnez une note",
        "Editar nota": "Modifier la note",
        "Visualizar nota": "Aperçu de la note",
        "Editor e visualização": "Éditeur et aperçu",
        "Desfazer": "Annuler",
        "Refazer": "Rétablir",
        "Cortar": "Couper",
        "Copiar": "Copier",
        "Colar": "Coller",
        "Selecionar tudo": "Tout sélectionner",
        "palavras": "mots",
        "carateres": "caractères",
        "linhas": "lignes",
        "Lista de tarefas": "Liste de tâches",
        "Tabela": "Tableau",
        "Separador horizontal": "Séparateur horizontal",
        "Coluna": "Colonne",
        "Conteúdo": "Contenu",
        "Título 4": "Titre 4",
        "Título 5": "Titre 5",
        "Título 6": "Titre 6",
        "Parágrafo": "Paragraphe",
        "Adicionar bloco": "Ajouter un bloc",
        "Linguagem": "Langage",
        "Descrição da imagem": "Description de l’image",
        "Localização da imagem": "Emplacement de l’image",
        "Adicionar linha": "Ajouter une ligne",
        "Adicionar coluna": "Ajouter une colonne",
        "Duplicar bloco": "Dupliquer le bloc",
        "Remover bloco": "Supprimer le bloc",
        "Guardar nota (⌘S)": "Enregistrer la note (⌘S)",
        "Exportar nota para PDF": "Exporter la note en PDF",
        "Alterações por guardar": "Modifications non enregistrées",
        "Fechar nota": "Fermer la note",
        "Título": "Titre",
        "Título 1": "Titre 1",
        "Título 2": "Titre 2",
        "Título 3": "Titre 3",
        "Negrito": "Gras",
        "Itálico": "Italique",
        "Rasurado": "Barré",
        "Código": "Code en ligne",
        "Lista": "Liste à puces",
        "Lista numerada": "Liste numérotée",
        "Citação": "Citation",
        "Ligação": "Lien",
        "Adicionar imagem": "Ajouter une image",
        "Bloco de código": "Bloc de code",
        "Idioma": "Langue",
        "Localização das notas": "Emplacement des notes",
        "Os notebooks, notas e respetivas imagens serão guardados nesta pasta.": "Les carnets, notes et leurs images seront enregistrés dans ce dossier.",
        "Nenhuma pasta selecionada": "Aucun dossier sélectionné",
        "Selecionar pasta…": "Choisir un dossier…",
        "Para atribuir um nome novo, use o botão Nova Pasta no seletor do Finder.": "Pour créer un nom, utilisez le bouton Nouveau dossier du sélecteur Finder.",
        "Estrutura planeada: Notebook / Nota / note.md + assets": "Structure : Carnet / Note / note.md + assets",
        "Concluído": "Terminé",
        "Escolher pasta das notas": "Choisir le dossier des notes",
        "Escolher": "Choisir",
        "Guardar alterações?": "Enregistrer les modifications ?",
        "A nota foi alterada desde a última gravação.": "La note a été modifiée depuis son dernier enregistrement.",
        "Guardar": "Enregistrer",
        "Não guardar": "Ne pas enregistrer",
        "Cancelar": "Annuler",
        "Guardar alterações antes de sair?": "Enregistrer avant de quitter ?",
        "Existem notas com alterações que ainda não foram guardadas.": "Certaines notes contiennent des modifications non enregistrées.",
        "Guardar tudo": "Tout enregistrer",
        "Não foi possível exportar o PDF": "Impossible d’exporter le PDF",
        "Exportar": "Exporter"
    ]
]
