#include "state.h"

#include "state.h"
#include <dlfcn.h>

Ptr (*gtk_application_new) (const char *, int);
int (*g_application_run) (Ptr, int, char **);
void (*g_application_quit) (Ptr);
void (*g_object_unref) (Ptr);
Ptr (*g_object_ref) (Ptr);
void (*g_object_set) (Ptr, const char *, ...);
void (*g_object_get) (Ptr, const char *, ...);
unsigned long (*g_signal_connect_data) (Ptr, const char *, void *, Ptr, void *, int);
void (*g_signal_emit_by_name) (Ptr, const char *, ...);
Ptr (*gtk_application_window_new) (Ptr);
void (*gtk_window_set_title) (Ptr, const char *);
void (*gtk_window_set_default_size) (Ptr, int, int);
void (*gtk_window_set_child) (Ptr, Ptr);
void (*gtk_window_present) (Ptr);
Ptr (*gtk_window_new) (void);
Ptr (*gtk_settings_get_default) (void);
Ptr (*gtk_window_get_focus) (Ptr);
void (*gtk_window_set_transient_for) (Ptr, Ptr);
void (*gtk_window_set_modal) (Ptr, gboolean);
void (*gtk_window_destroy) (Ptr);
Ptr (*gtk_message_dialog_new) (Ptr, int, int, int, const char *, ...);
void (*gtk_message_dialog_format_secondary_text) (Ptr, const char *, ...);
Ptr (*gtk_dialog_add_button) (Ptr, const char *, int);
Ptr (*gtk_box_new) (int, int);
void (*gtk_box_append) (Ptr, Ptr);
void (*gtk_box_remove) (Ptr, Ptr);
Ptr (*gtk_grid_new) (void);
void (*gtk_grid_attach) (Ptr, Ptr, int, int, int, int);
void (*gtk_grid_set_row_spacing) (Ptr, unsigned);
void (*gtk_grid_set_column_spacing) (Ptr, unsigned);
Ptr (*gtk_expander_new) (const char *);
void (*gtk_expander_set_child) (Ptr, Ptr);
void (*gtk_expander_set_label_widget) (Ptr, Ptr);
void (*gtk_expander_set_expanded) (Ptr, gboolean);
gboolean (*gtk_expander_get_expanded) (Ptr);
Ptr (*gtk_widget_get_first_child) (Ptr);
Ptr (*gtk_widget_get_next_sibling) (Ptr);
Ptr (*gtk_paned_new) (int);
void (*gtk_paned_set_start_child) (Ptr, Ptr);
void (*gtk_paned_set_end_child) (Ptr, Ptr);
void (*gtk_paned_set_position) (Ptr, int);
Ptr (*gtk_scrolled_window_new) (void);
void (*gtk_scrolled_window_set_child) (Ptr, Ptr);
void (*gtk_scrolled_window_set_policy) (Ptr, int, int);
Ptr (*gtk_scrolled_window_get_vadjustment) (Ptr);
void (*gtk_scrolled_window_set_vadjustment) (Ptr, Ptr);
void (*gtk_widget_set_hexpand) (Ptr, gboolean);
void (*gtk_widget_set_vexpand) (Ptr, gboolean);
void (*gtk_widget_set_size_request) (Ptr, int, int);
void (*gtk_widget_set_visible) (Ptr, gboolean);
gboolean (*gtk_widget_get_visible) (Ptr);
void (*gtk_widget_add_css_class) (Ptr, const char *);
void (*gtk_widget_remove_css_class) (Ptr, const char *);
gboolean (*gtk_widget_has_css_class) (Ptr, const char *);
void (*gtk_widget_set_tooltip_text) (Ptr, const char *);
int (*gtk_widget_get_width) (Ptr);
void (*gtk_widget_add_controller) (Ptr, Ptr);
Ptr (*gtk_event_controller_key_new) (void);
void (*gtk_event_controller_set_propagation_phase) (Ptr, int);
Ptr (*gtk_gesture_click_new) (void);
void (*gtk_gesture_single_set_button) (Ptr, unsigned);
void (*gtk_widget_set_parent) (Ptr, Ptr);
void (*gtk_widget_unparent) (Ptr);
Ptr (*gtk_popover_new) (void);
void (*gtk_popover_set_child) (Ptr, Ptr);
void (*gtk_popover_set_pointing_to) (Ptr, const void *);
void (*gtk_popover_popup) (Ptr);
void (*gtk_popover_popdown) (Ptr);
Ptr (*gtk_drop_target_new) (GType, int);
Ptr (*gtk_drag_source_new) (void);
void (*gtk_drag_source_set_actions) (Ptr, int);
GType (*gdk_file_list_get_type) (void);
Ptr (*g_value_get_boxed) (const void *);
const char * (*g_value_get_string) (const void *);
GType (*g_type_from_name) (const char *);
Ptr (*gdk_content_provider_new_typed) (GType, ...);
Ptr (*gtk_label_new) (const char *);
void (*gtk_label_set_text) (Ptr, const char *);
void (*gtk_label_set_xalign) (Ptr, float);
Ptr (*gtk_entry_new) (void);
Ptr (*gtk_search_entry_new) (void);
void (*gtk_search_entry_set_placeholder_text) (Ptr, const char *);
void (*gtk_entry_set_placeholder_text) (Ptr, const char *);
const char * (*gtk_editable_get_text) (Ptr);
void (*gtk_editable_set_text) (Ptr, const char *);
Ptr (*gtk_button_new_with_label) (const char *);
Ptr (*gtk_button_new_from_icon_name) (const char *);
void (*gtk_button_set_child) (Ptr, Ptr);
Ptr (*gtk_check_button_new_with_label) (const char *);
void (*gtk_check_button_set_active) (Ptr, gboolean);
gboolean (*gtk_check_button_get_active) (Ptr);
void (*gtk_button_set_label) (Ptr, const char *);
void (*gtk_button_set_icon_name) (Ptr, const char *);
Ptr (*gtk_text_view_new) (void);
void (*gtk_text_view_set_monospace) (Ptr, gboolean);
void (*gtk_text_view_set_wrap_mode) (Ptr, int);
void (*gtk_text_view_set_left_margin) (Ptr, int);
void (*gtk_text_view_set_right_margin) (Ptr, int);
void (*gtk_text_view_set_top_margin) (Ptr, int);
Ptr (*gtk_text_view_get_buffer) (Ptr);
Ptr (*gtk_text_buffer_get_tag_table) (Ptr);
Ptr (*gtk_text_buffer_new) (Ptr);
void (*gtk_text_view_set_buffer) (Ptr, Ptr);
void (*gtk_text_buffer_set_text) (Ptr, const char *, int);
void (*gtk_text_buffer_get_bounds) (Ptr, void *, void *);
char * (*gtk_text_buffer_get_text) (Ptr, const void *, const void *, gboolean);
void (*gtk_text_buffer_insert_at_cursor) (Ptr, const char *, int);
void (*gtk_text_buffer_get_iter_at_offset) (Ptr, void *, int);
void (*gtk_text_buffer_select_range) (Ptr, const void *, const void *);
gboolean (*gtk_text_buffer_get_selection_bounds) (Ptr, void *, void *);
void (*gtk_text_buffer_delete) (Ptr, void *, void *);
void (*gtk_text_buffer_get_end_iter) (Ptr, void *);
void (*gtk_text_buffer_insert) (Ptr, void *, const char *, int);
int (*gtk_text_buffer_get_char_count) (Ptr);
Ptr (*gtk_text_buffer_get_insert) (Ptr);
void (*gtk_text_buffer_get_iter_at_mark) (Ptr, void *, Ptr);
int (*gtk_text_iter_get_line) (const void *);
Ptr (*gtk_text_buffer_create_tag) (Ptr, const char *, const char *, ...);
void (*gtk_text_buffer_apply_tag_by_name) (Ptr, const char *, const void *, const void *);
void (*gtk_text_buffer_remove_all_tags) (Ptr, const void *, const void *);
void (*gtk_text_buffer_set_enable_undo) (Ptr, gboolean);
Ptr (*gtk_text_buffer_create_child_anchor) (Ptr, void *);
void (*gtk_text_view_add_child_at_anchor) (Ptr, Ptr, Ptr);
Ptr (*gtk_picture_new_for_filename) (const char *);
void (*gtk_picture_set_content_fit) (Ptr, int);
void (*gtk_text_view_scroll_to_iter) (Ptr, void *, double, gboolean, double, double);
void (*gtk_text_view_set_editable) (Ptr, gboolean);
void (*gtk_text_view_set_cursor_visible) (Ptr, gboolean);
Ptr (*gtk_stack_new) (void);
Ptr (*gtk_stack_add_titled) (Ptr, Ptr, const char *, const char *);
void (*gtk_stack_set_visible_child_name) (Ptr, const char *);
const char * (*gtk_stack_get_visible_child_name) (Ptr);
Ptr (*gtk_stack_switcher_new) (void);
void (*gtk_stack_switcher_set_stack) (Ptr, Ptr);
Ptr (*gtk_drop_down_new_from_strings) (const char *const *);
void (*gtk_drop_down_set_selected) (Ptr, guint);
guint (*gtk_drop_down_get_selected) (Ptr);
void (*g_free) (Ptr);
void (*g_error_free) (Ptr);
guint (*g_timeout_add) (guint, void *, Ptr);
gboolean (*g_source_remove) (guint);
Ptr (*gtk_image_new_from_file) (const char *);
Ptr (*gtk_image_new_from_icon_name) (const char *);
void (*gtk_image_set_pixel_size) (Ptr, int);
void (*gtk_widget_set_margin_start) (Ptr, int);
void (*gtk_widget_set_margin_end) (Ptr, int);
void (*gtk_widget_set_margin_top) (Ptr, int);
void (*gtk_widget_set_margin_bottom) (Ptr, int);
Ptr (*gtk_separator_new) (int);
Ptr (*gtk_css_provider_new) (void);
void (*gtk_css_provider_load_from_path) (Ptr, const char *);
Ptr (*gdk_display_get_default) (void);
Ptr (*gdk_display_get_clipboard) (Ptr);
Ptr (*gdk_clipboard_get_formats) (Ptr);
gboolean (*gdk_content_formats_contain_gtype) (Ptr, GType);
GType (*gdk_texture_get_type) (void);
void (*gdk_clipboard_read_texture_async) (Ptr, Ptr, void *, Ptr);
Ptr (*gdk_clipboard_read_texture_finish) (Ptr, Ptr, Ptr *);
gboolean (*gdk_texture_save_to_png) (Ptr, const char *);
void (*gtk_style_context_add_provider_for_display) (Ptr, Ptr, guint);
void (*gtk_style_context_remove_provider_for_display) (Ptr, Ptr);
Ptr (*gtk_file_chooser_native_new) (const char *, Ptr, int, const char *, const char *);
Ptr (*gtk_file_chooser_get_file) (Ptr);
char * (*g_file_get_path) (Ptr);
void (*gtk_native_dialog_show) (Ptr);
void (*gtk_file_chooser_set_current_name) (Ptr, const char *);
Ptr (*g_file_new_for_path) (const char *);
gboolean (*g_file_trash) (Ptr, Ptr, Ptr);
Ptr (*cairo_pdf_surface_create) (const char *, double, double);
Ptr (*cairo_create) (Ptr);
void (*cairo_select_font_face) (Ptr, const char *, int, int);
void (*cairo_set_font_size) (Ptr, double);
void (*cairo_move_to) (Ptr, double, double);
void (*cairo_show_text) (Ptr, const char *);
void (*cairo_show_page) (Ptr);
void (*cairo_destroy) (Ptr);
void (*cairo_surface_destroy) (Ptr);
void (*cairo_surface_finish) (Ptr);
int (*cairo_surface_status) (Ptr);

void load_symbol(void **target, const char *name) {
    *target = dlsym(RTLD_DEFAULT, name);
    if (!*target) die(name);
}
void load_gtk(void) {
    state.gtk = dlopen("libgtk-4.so.1", RTLD_NOW | RTLD_GLOBAL);
    if (!state.gtk) die("GTK 4 não está instalada (libgtk-4.so.1)");
    LOAD(gtk_application_new); LOAD(g_application_run); LOAD(g_application_quit); LOAD(g_object_unref); LOAD(g_object_ref); LOAD(g_object_set); LOAD(g_object_get);
    LOAD(g_signal_connect_data); LOAD(g_signal_emit_by_name); LOAD(gtk_application_window_new); LOAD(gtk_window_new); LOAD(gtk_settings_get_default); LOAD(gtk_window_get_focus);
    LOAD(gtk_window_set_transient_for); LOAD(gtk_window_set_modal); LOAD(gtk_window_set_title);
    LOAD(gtk_window_destroy);
    LOAD(gtk_message_dialog_new); LOAD(gtk_message_dialog_format_secondary_text);
    LOAD(gtk_dialog_add_button);
    LOAD(gtk_window_set_default_size); LOAD(gtk_window_set_child); LOAD(gtk_window_present);
    LOAD(gtk_box_new); LOAD(gtk_box_append); LOAD(gtk_box_remove); LOAD(gtk_widget_get_first_child); LOAD(gtk_widget_get_next_sibling);
    LOAD(gtk_grid_new); LOAD(gtk_grid_attach); LOAD(gtk_grid_set_row_spacing); LOAD(gtk_grid_set_column_spacing);
    LOAD(gtk_expander_new); LOAD(gtk_expander_set_child); LOAD(gtk_expander_set_label_widget);
    LOAD(gtk_expander_set_expanded); LOAD(gtk_expander_get_expanded);
    LOAD(gtk_paned_new); LOAD(gtk_paned_set_start_child);
    LOAD(gtk_paned_set_end_child); LOAD(gtk_paned_set_position); LOAD(gtk_scrolled_window_new);
    LOAD(gtk_scrolled_window_set_child); LOAD(gtk_scrolled_window_set_policy);
    LOAD(gtk_scrolled_window_get_vadjustment); LOAD(gtk_scrolled_window_set_vadjustment);
    LOAD(gtk_widget_set_hexpand); LOAD(gtk_widget_set_vexpand);
    LOAD(gtk_widget_set_size_request); LOAD(gtk_widget_set_visible); LOAD(gtk_widget_get_visible);
    LOAD(gtk_widget_add_css_class); LOAD(gtk_widget_remove_css_class); LOAD(gtk_widget_has_css_class);
    LOAD(gtk_widget_set_tooltip_text);
    LOAD(gtk_widget_get_width); LOAD(gtk_label_new);
    LOAD(gtk_widget_add_controller); LOAD(gtk_event_controller_key_new); LOAD(gtk_event_controller_set_propagation_phase);
    LOAD(gtk_gesture_click_new); LOAD(gtk_gesture_single_set_button);
    LOAD(gtk_widget_set_parent); LOAD(gtk_widget_unparent);
    LOAD(gtk_popover_new); LOAD(gtk_popover_set_child); LOAD(gtk_popover_set_pointing_to); LOAD(gtk_popover_popup); LOAD(gtk_popover_popdown);
    LOAD(gtk_drop_target_new); LOAD(gtk_drag_source_new); LOAD(gtk_drag_source_set_actions);
    LOAD(gdk_file_list_get_type); LOAD(g_value_get_boxed); LOAD(g_value_get_string); LOAD(g_type_from_name);
    LOAD(gdk_content_provider_new_typed);
    LOAD(gtk_label_set_text); LOAD(gtk_label_set_xalign); LOAD(gtk_entry_new); LOAD(gtk_search_entry_new);
    LOAD(gtk_search_entry_set_placeholder_text);
    LOAD(gtk_entry_set_placeholder_text); LOAD(gtk_editable_get_text); LOAD(gtk_editable_set_text);
    LOAD(gtk_button_new_with_label); LOAD(gtk_button_new_from_icon_name); LOAD(gtk_button_set_child);
    LOAD(gtk_button_set_label); LOAD(gtk_button_set_icon_name); LOAD(gtk_check_button_new_with_label);
    LOAD(gtk_check_button_set_active); LOAD(gtk_check_button_get_active); LOAD(gtk_text_view_new);
    LOAD(gtk_text_view_set_monospace); LOAD(gtk_text_view_set_wrap_mode);
    LOAD(gtk_text_view_set_left_margin); LOAD(gtk_text_view_set_right_margin);
    LOAD(gtk_text_view_set_top_margin); LOAD(gtk_text_view_get_buffer); LOAD(gtk_text_buffer_get_tag_table); LOAD(gtk_text_buffer_new); LOAD(gtk_text_view_set_buffer); LOAD(gtk_text_buffer_set_text);
    LOAD(gtk_text_buffer_get_bounds); LOAD(gtk_text_buffer_get_text); LOAD(gtk_text_buffer_insert_at_cursor);
    LOAD(gtk_text_buffer_get_iter_at_offset); LOAD(gtk_text_buffer_select_range); LOAD(gtk_text_view_scroll_to_iter);
    LOAD(gtk_text_buffer_get_selection_bounds); LOAD(gtk_text_buffer_delete);
    LOAD(gtk_text_buffer_get_end_iter); LOAD(gtk_text_buffer_insert); LOAD(gtk_text_buffer_get_char_count);
    LOAD(gtk_text_buffer_get_insert); LOAD(gtk_text_buffer_get_iter_at_mark); LOAD(gtk_text_iter_get_line);
    LOAD(gtk_text_buffer_create_tag);
    LOAD(gtk_text_buffer_apply_tag_by_name);
    LOAD(gtk_text_buffer_remove_all_tags);
    LOAD(gtk_text_buffer_set_enable_undo);
    LOAD(gtk_text_buffer_create_child_anchor); LOAD(gtk_text_view_add_child_at_anchor);
    LOAD(gtk_picture_new_for_filename); LOAD(gtk_picture_set_content_fit);
    LOAD(gtk_text_view_set_editable); LOAD(gtk_text_view_set_cursor_visible); LOAD(gtk_stack_new);
    LOAD(gtk_stack_add_titled); LOAD(gtk_stack_set_visible_child_name); LOAD(gtk_stack_get_visible_child_name); LOAD(gtk_stack_switcher_new);
    LOAD(gtk_stack_switcher_set_stack); LOAD(gtk_drop_down_new_from_strings); LOAD(gtk_drop_down_set_selected);
    LOAD(gtk_drop_down_get_selected); LOAD(g_free); LOAD(g_error_free);
    LOAD(g_timeout_add); LOAD(g_source_remove); LOAD(gtk_file_chooser_native_new);
    LOAD(gtk_file_chooser_get_file); LOAD(g_file_get_path); LOAD(gtk_native_dialog_show);
    LOAD(gtk_file_chooser_set_current_name);
    LOAD(g_file_new_for_path); LOAD(g_file_trash);
    LOAD(cairo_pdf_surface_create); LOAD(cairo_create); LOAD(cairo_select_font_face);
    LOAD(cairo_set_font_size); LOAD(cairo_move_to); LOAD(cairo_show_text); LOAD(cairo_show_page);
    LOAD(cairo_destroy); LOAD(cairo_surface_finish); LOAD(cairo_surface_destroy); LOAD(cairo_surface_status);
    LOAD(gtk_image_new_from_file); LOAD(gtk_image_new_from_icon_name); LOAD(gtk_image_set_pixel_size);
    LOAD(gtk_widget_set_margin_start);
    LOAD(gtk_widget_set_margin_end); LOAD(gtk_widget_set_margin_top); LOAD(gtk_widget_set_margin_bottom);
    LOAD(gtk_separator_new); LOAD(gtk_css_provider_new); LOAD(gtk_css_provider_load_from_path);
    LOAD(gdk_display_get_default); LOAD(gdk_display_get_clipboard); LOAD(gdk_clipboard_get_formats);
    LOAD(gdk_content_formats_contain_gtype); LOAD(gdk_texture_get_type); LOAD(gdk_clipboard_read_texture_async);
    LOAD(gdk_clipboard_read_texture_finish); LOAD(gdk_texture_save_to_png); LOAD(gtk_style_context_add_provider_for_display);
    LOAD(gtk_style_context_remove_provider_for_display);
}
