#include "state.h"

State state;

const char *tr(const char *pt) {
    struct Translation { const char *pt, *en, *fr; };
    static const struct Translation values[] = {
        {"Novo notebook", "New notebook", "Nouveau carnet"}, {"Nova nota", "New note", "Nouvelle note"},
        {"Templates", "Templates", "Modèles"}, {"Abrir…", "Open…", "Ouvrir…"},
        {"Preferências", "Preferences", "Préférences"}, {"Pesquisar", "Find", "Rechercher"},
        {"Histórico", "History", "Historique"}, {"Remover", "Delete", "Supprimer"},
        {"Guardar", "Save", "Enregistrer"}, {"Pesquisar notas", "Search notes", "Rechercher des notes"},
        {"Título da nota", "Note title", "Titre de la note"},
        {"Tags separadas por vírgulas", "Comma-separated tags", "Tags séparés par des virgules"},
        {"Editor", "Editor", "Éditeur"}, {"Visual", "Visual", "Visuel"}, {"Dividido", "Split", "Partagé"},
        {"Imagem…", "Image…", "Image…"}, {"NOTEMD · BIBLIOTECA", "NOTEMD · LIBRARY", "NOTEMD · BIBLIOTHÈQUE"},
        {"Ficheiros externos", "External files", "Fichiers externes"},
        {"Crie ou abra uma nota", "Create or open a note", "Créez ou ouvrez une note"},
        {"Sistema", "System", "Système"}, {"Tema do editor", "Editor theme", "Thème de l’éditeur"},
        {"Gravação automática", "Automatic saving", "Enregistrement automatique"},
        {"Aparência e armazenamento", "Appearance and storage", "Apparence et stockage"},
        {"Selecionar pasta das notas…", "Choose notes folder…", "Choisir le dossier des notes…"},
        {"Cor da nota", "Note color", "Couleur de la note"}, {"Cor do notebook", "Notebook color", "Couleur du carnet"},
        {"Mover nota ativa para", "Move active note to", "Déplacer la note active vers"},
        {"Tags", "Tags", "Tags"}, {"Sem tags", "No tags", "Aucun tag"},
        {"Selecione uma nota", "Select a note", "Sélectionnez une note"},
        {"Nova nota a partir de template", "New note from template", "Nouvelle note depuis un modèle"},
        {"Escolha um template", "Choose a template", "Choisissez un modèle"},
        {"Nota vazia", "Blank note", "Note vide"}, {"Reunião", "Meeting", "Réunion"},
        {"Diário", "Daily note", "Note quotidienne"}, {"Projeto", "Project", "Projet"},
        {"Checklist", "Checklist", "Checklist"}, {"Histórico de versões", "Version history", "Historique des versions"},
        {"Ainda não existem versões anteriores.", "There are no previous versions yet.", "Il n’existe pas encore de version précédente."},
        {"Restaurar esta versão", "Restore this version", "Restaurer cette version"},
        {"Apagar esta versão", "Delete this version", "Supprimer cette version"},
        {"Pesquisar e substituir", "Find and replace", "Rechercher et remplacer"},
        {"Substituir por", "Replace with", "Remplacer par"},
        {"Correspondência seguinte", "Next match", "Correspondance suivante"},
        {"Substituir correspondência atual", "Replace current match", "Remplacer la correspondance actuelle"},
        {"Substituir todas as correspondências", "Replace all matches", "Remplacer toutes les correspondances"},
        {"Fechar pesquisa", "Close search", "Fermer la recherche"},
        {"Parágrafo", "Paragraph", "Paragraphe"}, {"Título", "Heading", "Titre"},
        {"Lista", "Bullet list", "Liste à puces"}, {"Tarefa", "Task", "Tâche"},
        {"Citação", "Quote", "Citation"}, {"Código", "Code", "Code"}, {"Tabela", "Table", "Tableau"},
        {"Separador", "Divider", "Séparateur"}, {"Duplicar bloco", "Duplicate block", "Dupliquer le bloc"},
        {"Remover bloco", "Delete block", "Supprimer le bloc"},
        {"Adicionar linha", "Add row", "Ajouter une ligne"}, {"Adicionar coluna", "Add column", "Ajouter une colonne"},
        {"Marcar tarefa como concluída", "Mark task as completed", "Marquer la tâche comme terminée"},
        {"Negrito", "Bold", "Gras"}, {"Itálico", "Italic", "Italique"}, {"Ligação", "Link", "Lien"},
        {"Título 1", "Heading 1", "Titre 1"}, {"Título 2", "Heading 2", "Titre 2"},
        {"Título 3", "Heading 3", "Titre 3"}, {"Título 4", "Heading 4", "Titre 4"},
        {"Título 5", "Heading 5", "Titre 5"}, {"Título 6", "Heading 6", "Titre 6"},
        {"Rasurado", "Strikethrough", "Barré"}, {"Lista numerada", "Numbered list", "Liste numérotée"},
        {"Cor do texto", "Text color", "Couleur du texte"}, {"Sem cor", "No color", "Sans couleur"},
        {"Vermelho", "Red", "Rouge"}, {"Laranja", "Orange", "Orange"}, {"Amarelo", "Yellow", "Jaune"},
        {"Verde", "Green", "Vert"}, {"Azul", "Blue", "Bleu"}, {"Roxo", "Purple", "Violet"},
        {"Abrir ficheiro Markdown", "Open Markdown file", "Ouvrir un fichier Markdown"},
        {"Inserir imagem", "Insert image", "Insérer une image"},
        {"Exportar HTML", "Export HTML", "Exporter en HTML"}, {"Exportar PDF", "Export PDF", "Exporter en PDF"},
        {"Exportar DOCX", "Export DOCX", "Exporter en DOCX"}, {"Exportar", "Export", "Exporter"},
        {"Cancelar", "Cancel", "Annuler"}, {"Abrir", "Open", "Ouvrir"}, {"Inserir", "Insert", "Insérer"},
        {"Renomear notebook", "Rename notebook", "Renommer le carnet"}, {"Renomear", "Rename", "Renommer"},
        {"Ligações", "Links", "Liens"}, {"Pronto", "Ready", "Prêt"},
        {"Guardado", "Saved", "Enregistré"}, {"Erro ao guardar", "Could not save", "Impossible d’enregistrer"},
        {"Imagem copiada para assets", "Image copied to assets", "Image copiée dans assets"},
        {"Imagem colada e guardada em assets", "Image pasted and saved to assets", "Image collée et enregistrée dans assets"},
        {"Tema aplicado", "Theme applied", "Thème appliqué"},
        {"Gravação automática ativada", "Automatic saving enabled", "Enregistrement automatique activé"},
        {"Gravação automática desativada", "Automatic saving disabled", "Enregistrement automatique désactivé"},
        {"Sem mais correspondências", "No more matches", "Aucune autre correspondance"},
        {"Correspondência encontrada", "Match found", "Correspondance trouvée"},
        {"Texto não encontrado", "Text not found", "Texte introuvable"},
        {"Correspondência substituída", "Match replaced", "Correspondance remplacée"},
        {"Ocultar biblioteca", "Hide library", "Masquer la bibliothèque"},
        {"Mostrar biblioteca", "Show library", "Afficher la bibliothèque"},
        {"palavras", "words", "mots"}, {"carateres", "characters", "caractères"}, {"linhas", "lines", "lignes"},
        {"a guardar…", "saving…", "enregistrement…"},
        {"alterações por guardar", "unsaved changes", "modifications non enregistrées"},
        {"Alterações por guardar", "Unsaved changes", "Modifications non enregistrées"},
        {"Guardar alterações?", "Save changes?", "Enregistrer les modifications ?"},
        {"A nota foi alterada desde a última gravação.", "The note has changed since it was last saved.", "La note a été modifiée depuis son dernier enregistrement."},
        {"Não guardar", "Don't save", "Ne pas enregistrer"},
        {"Versão guardada", "Saved version", "Version enregistrée"},
        {"Versão atual", "Current version", "Version actuelle"},
        {"Selecione uma versão para a pré-visualizar. Restaurar não grava automaticamente.",
         "Select a version to preview it. Restoring does not save automatically.",
         "Sélectionnez une version pour la prévisualiser. La restauration n’enregistre pas automatiquement."},
        {"Crie uma versão editando e guardando a nota.", "Create a version by editing and saving the note.",
         "Créez une version en modifiant puis en enregistrant la note."},
        {"Criar esta nota", "Create this note", "Créer cette note"},
        {"Linguagem", "Language", "Langage"},
        {"Descrição da imagem", "Image description", "Description de l’image"},
        {"Localização da imagem", "Image location", "Emplacement de l’image"}
    };
    int column = strcmp(state.language, "en") == 0 ? 1 : strcmp(state.language, "fr") == 0 ? 2 : 0;
    for (size_t index = 0; index < sizeof values / sizeof values[0]; index++) if (strcmp(values[index].pt, pt) == 0)
        return column == 1 ? values[index].en : column == 2 ? values[index].fr : values[index].pt;
    return pt;
}
